version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coloc-api
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      # - /etc/letsencrypt/live/tanguyblondinprog.ovh:/app/cert:ro