version: '3.9'

services:

  db:
    image: postgres
    restart: always
    container_name: coloc_db
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  adminer:
    image: adminer
    restart: always
    container_name: coloc-pg-adminer
    ports:
      - 8080:8080
    depends_on:
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coloc-api
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src